sudo: true
# Use C as a dummy language to avoid Travis-CI setting up a virtualenv
# for us, etc.
language: c
before_install:
  # Remove some packages that actively depend on locales working properly.
  - sudo apt-get --quiet=2 remove postgresql-9.1 postgresql-contrib-9.1 postgresql-9.2 postgresql-contrib-9.2 postgresql-9.3 postgresql-contrib-9.3 postgresql-9.4 postgresql-contrib-9.4 >/dev/null
  # We need at least Vivid for python3-stdeb
  - sudo rm -f /etc/apt/sources.list
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ vivid main universe' | sudo dd of=/etc/apt/sources.list
  - echo 'deb http://us.archive.ubuntu.com/ubuntu/ vivid-updates main universe' | sudo dd of=/etc/apt/sources.list conv=notrunc oflag=append
  # Tell dpkg it is OK to choose the new config files, without prompting.
  - echo 'Dpkg::Options { "--force-confdef"; "--force-confnew"; }' | sudo dd of=/etc/apt/apt.conf.d/99conf
  - sudo apt-get --quiet=2 update
  - sudo apt-get --quiet=2 -y --force-yes dist-upgrade
  # Make sure locales are in a healthy shape.
  - echo 'en_US.UTF-8 UTF-8' | sudo dd of=/etc/locale.gen
  - sudo /usr/sbin/locale-gen
  # Install some additional dependencies.
  - sudo apt-get install python3-six debootstrap dpkg-dev lsb-release python python-stdeb python-wheel python3 python3-stdeb python3-wheel schroot tox
before_script:
  - export CH_GROUPS="$(id -gn),root"
  - sudo -E ./mkchroot.sh
script:
  - tox
after_script:
  - sudo -E ./rmchroot.sh
